#!/usr/bin/env python3
"""
Utility script to convert icon PNG files to base64-encoded strings
for embedding directly in Python code.

Run this script to generate embedded_icons.py with base64-encoded icon data.
"""

import os
import base64
from pathlib import Path

def convert_icon_to_base64(icon_path):
    """Convert a PNG icon file to a base64-encoded string."""
    with open(icon_path, 'rb') as f:
        icon_data = f.read()
        base64_data = base64.b64encode(icon_data).decode('utf-8')
    return base64_data

def generate_embedded_icons():
    """Generate embedded_icons.py with base64-encoded icons."""
    icons_dir = Path(__file__).parent / 'scalebaron' / 'icons'
    icon_files = {
        'summarize': 'summarize.png',
        'preview': 'preview.png',
        'add_label': 'add_label.png',
        'save': 'save.png',
        'batch': 'batch.png',
        'progress': 'progress.png'
    }
    
    # Also check for label.png as fallback for add_label
    if not (icons_dir / 'add_label.png').exists() and (icons_dir / 'label.png').exists():
        icon_files['add_label'] = 'label.png'
    
    embedded_icons = {}
    for key, filename in icon_files.items():
        icon_path = icons_dir / filename
        if icon_path.exists():
            print(f"Converting {filename}...")
            embedded_icons[key] = convert_icon_to_base64(icon_path)
        else:
            print(f"Warning: {filename} not found, skipping...")
    
    # Generate the Python file
    output_file = Path(__file__).parent / 'scalebaron' / 'embedded_icons.py'
    
    with open(output_file, 'w') as f:
        f.write('"""\n')
        f.write('Embedded button icons as base64-encoded strings.\n')
        f.write('This file is auto-generated by convert_icons_to_base64.py\n')
        f.write('"""\n\n')
        f.write('EMBEDDED_ICONS = {\n')
        for key, base64_data in embedded_icons.items():
            f.write(f"    '{key}': '{base64_data}',\n")
        f.write('}\n')
    
    print(f"\n✅ Generated {output_file}")
    print(f"   Embedded {len(embedded_icons)} icons")

if __name__ == '__main__':
    generate_embedded_icons()


