name: JOSS Paper Build

on:
  push:
    paths:
      - paper.md
      - .github/workflows/joss.yml
  pull_request:
    paths:
      - paper.md
      - .github/workflows/joss.yml

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Build JOSS paper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter numpy matplotlib pandas pillow openpyxl scipy

      - name: Build paper
        uses: openjournals/openjournals-joss-action@v1.2.0
